### ISSUE TITLE
pre tag does word wrap

### ISSUE THREAD

**Issue by berryma4** [Olog/logbook#31]
need to add to the end of stlye.css and print_style.css:
```css
pre {
  white-space: pre-wrap;
  word-break: normal;
}
```
